config/routes.rb
Rails.application.routes.draw do
  root to: "items#index"
  get 'search', to: 'items#search'
  devise_for :users
  resources :items
  resources :categories, expect: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  belongs_to :user
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  belongs_to :category

  validates :season_id, numericality: { other_than: 1, message: 'select' }
  validates :image, presence: true
  validates :category_id, numericality: { other_than: 1, message: 'select' }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :season
end

app/models/season.rb
class Season < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'S/S' },
    { id: 3, name: 'A/W' },
    { id: 4, name: 'AllSeason' }

  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :items
  has_many :categories

  with_options presence: true do
    validates :nickname, length: { minimum: 1, maximum: 8}
    validates :password, format: { with: /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/, message: 'Include both letters and numbers' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :text])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.where(user_id: current_user.id)
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render 'index'
    end
  end

  def destroy
    set_category
    if @category.destroy
      redirect_to categories_path
    else
      render 'index'
    end
  end

  def update
    set_category
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'index'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name).merge(user_id: current_user.id)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @item = Item.all.where(user_id: current_user.id).includes(:category)
      @item = @item.order('created_at DESC')
      @p = @item.ransack(params[:q])
      set_category_column
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render 'edit'
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  def search
    @item = Item.all.where(user_id: current_user.id)
    @p = @item.ransack(params[:q])
    @results = @p.result.includes(:category).order('created_at DESC')
  end

  private

  def set_category_column
    @category_name = Category.where(user_id: current_user.id).select('name').distinct
  end

  def item_params
    params.require(:item).permit(:explanation, :category_id, :season_id, :brand, :purchase_day, :price, :place, :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_user
    redirect_to root_path unless user_signed_in? && current_user.id == @item.user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/index.html.erb
<div class="container">
<%= render "shared/header" %>

<%# カテゴリー追加form %>
<div class="categories-new">
  <%= form_with model: @category, id: "form-category", local: true do |f| %>
    <div class="field">
      <%= f.label :name, "カテゴリーを追加" %><br>
      <%= f.text_field :name, id: "name" %>
      <%= f.submit "Create", class:"categories-input-btn", id:"categories-input" %>
    </div>
  <%end%>
</div>
<%# //カテゴリー追加form %>

<div class="categories-show">
  <%# 登録したカテゴリー展開 %>
  <table class="category-table">
    <tbody id="list-category">
    <% if @categories.present? %>
    <% @categories.each do |category|%>
    <%= form_with model: category, local: true do |f| %>
      <tr>
        <td><%= f.text_area :name, class:"small-items-text", id:"item-info", placeholder:"" ,rows:"1" ,maxlength:"50" %></td>
        <td><%= f.submit "Edit", class: "category-edit-btn" %></td>
        <td><%= link_to 'Destroy', category_path(category.id), method: :delete, class:'category-destroy' %></td>
      </tr>
    <%end%>
    <%end%>
    <%end%>
    </tbody>
  </table>
  <%# //登録したカテゴリー展開 %>
  <div class="input-btn-contents">
    <%=link_to 'もどる', root_path, class:"category-back-btn" %>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "shared/header" %>
<%= render "shared/nav" %>

<div class="item-main">
  <h2 class="new-item-title">アイテム情報を入力</h2>
  <%= form_with model: @item, local: true do |f| %>

  <%= render "shared/error_item_messages", model: f.object %> 

  
  <div class="images-item">
    <div class="weight-bold-text">
        アイテム画像
        <span class="indispensable">※必須</span>
    </div>
    <%= f.file_field :image, accept: '.jpeg, .jpg, .gif, .png, .bmp', id:"item-imag" %>
  </div>

  <div class="explanation-item">
    <div class="weight-bold-text">
      アイテム説明
      <span class="indispensable">※任意</span>
    </div>
    <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"商品の説明（素材や合わせ方など自由に使ってください)" ,rows:"6" ,maxlength:"300" %>
  </div>
  <div class="category-item">
    <div class="weight-bold-text">
      カテゴリー
      <span class="indispensable">(※必須)</span>
    </div>
    <%= f.collection_select(:category_id, Category.all.where(user_id: current_user.id), :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>
  <div class="season-item">
    <div class="weight-bold-text">
      シーズン
      <span class="indispensable">(※必須)</span>
    </div>
    <%= f.collection_select(:season_id, Season.all, :id, :name, {}, {class:"select-box", id:"season-category"}) %>
  </div>
  <div class="bland-item">
    <div class="weight-bold-text">
      ブランド
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :brand, class:"small-items-text", id:"item-info", placeholder:"ブランド名" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="place-item">
    <div class="weight-bold-text">
      購入されたお店
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :place, class:"small-items-text", id:"item-info", placeholder:"名前またはサイトURLなど" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="price-item">
    <div class="weight-bold-text">
      購入価格
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :price, class:"price-items-text", id:"item-info", placeholder:"半角数字" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="form-group">
    <div class='weight-bold-text'>
      購入日
      <span class="indispensable">(※任意)</span>
    </div>
    <div class='input-date'>
      <%= raw sprintf(
        f.date_select(
          :purchase_day,
          class:'select-date',
          id:"pachase-date",
          use_month_numbers: true,
          prompt:'--',
          start_year: (Time.now.year) - 5,
          end_year: (Time.now.year),
          date_separator: '%s'),
        "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
  </div>

  <div class="input-btn-contents">
    <%= f.submit "変更する" ,class:"input-btn" %>

    <%=link_to 'もどる', item_path(@item.id), class:"back-btn" %>
  </div>

  <%end%>
</div>

app/views/items/index.html.erb
<body>
<!-- ▼ヘッダー▼ -->
<header>
<div id="top">
  <%= render "shared/header" %>
  <%= render "shared/nav" %>
</div>
</header>
<body>
<% unless user_signed_in? %>
<%# ログインしていない場合 %>
<div class="main-header">
  <%= image_tag "cabinet-1853504_1920.jpg", class:"header-pict" %>
<h2 class="introduction">アプリ紹介</h2>
  <p class="des">
  このアプリは服管理アプリです。<br>
  お使いの場合はスマートフォンを推奨しております。<br>
  あなたが持っている服を写真やカテゴリー別に保存することで自分の持っている服を管理する事ができます。<br>
  店先で自分が持っている服を確認したい時、今日どんな服を着て行こうか悩んでいる方の手助けになればと思っております。
  </p>
<%# // ログインしていない場合 %>
<%else%>
<%# ログインしている場合 %>
<div class="main">
  <div class='post-btn'>
    <span class="post-btn-text">NEW ITEM</span>
    <%= link_to image_tag('カメラアイコン8.jpeg', class: "post-btn-icon"), new_item_path %>
  </div>
  <div class="left-nav">
    <%= search_form_for(@p, url: search_path) do |f| %>
      <%= f.label :category_name_eq, 'カテゴリー：' %>
      <%= f.collection_select :category_name_eq, @category_name, :name, :name %>
      <br>
    <%= f.submit '検索', class:"search-btn" %>
    <% end %> 
  </div>
  <h2 class="title">NEW ARRIVAL</h2>
  <div class="item_entry">
	  <ul class="item-lists">
      <%= render "shared/item"%>
    </ul>
  </div>
</div>
<%end%>
<%# // ログインしている場合 %>
</body>

app/views/items/new.html.erb
<%= render "shared/header" %>
<%= render "shared/nav" %>

<div class="item-main">
  <h2 class="new-item-title">アイテム情報を入力</h2>
  <%= form_with model: @item, local: true do |f| %>

  <%= render "shared/error_item_messages", model: f.object %> 

  <div class="images-item">
    <div class="weight-bold-text">
        アイテム画像
        <span class="indispensable">※必須 (一枚だけ)</span>
    </div>
    <%= f.file_field :image, accept: '.jpeg, .jpg, .gif, .png, .bmp', id:"item-imag" %>
  </div>

  <div class="explanation-item">
    <div class="weight-bold-text">
      アイテム説明
      <span class="indispensable">※任意</span>
    </div>
    <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"商品の説明（素材や合わせ方など自由に使ってください)" ,rows:"6" ,maxlength:"300" %>
  </div>
  <div class="category-item">
    <div class="weight-bold-text">
      カテゴリー
      <span class="indispensable">(※必須)</span>
      <span><%= link_to '追加はこちら', categories_path, class: "categories-path-btn" %></span>
    </div>
    <%= f.collection_select(:category_id, Category.all.where(user_id: current_user.id), :id, :name, {}, {class:"select-box", id:"item-category"}) %>
  </div>
  <div class="season-item">
    <div class="weight-bold-text">
      シーズン
      <span class="indispensable">(※必須)</span>
    </div>
    <%= f.collection_select(:season_id, Season.all, :id, :name, {}, {class:"select-box", id:"season-category"}) %>
  </div>
  <div class="bland-item">
    <div class="weight-bold-text">
      ブランド
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :brand, class:"small-items-text", id:"item-info", placeholder:"ブランド名" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="place-item">
    <div class="weight-bold-text">
      購入されたお店
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :place, class:"small-items-text", id:"item-info", placeholder:"名前またはサイトURLなど" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="price-item">
    <div class="weight-bold-text">
      購入価格
      <span class="indispensable">(※任意)</span>
    </div>
    <%= f.text_area :price, class:"price-items-text", id:"item-info", placeholder:"半角数字" ,rows:"1" ,maxlength:"50" %>
  </div>
  <div class="form-group">
    <div class='weight-bold-text'>
      購入日
      <span class="indispensable">(※任意)</span>
    </div>
    <div class='input-date'>
      <%= raw sprintf(
        f.date_select(
          :purchase_day,
          class:'select-date',
          id:"pachase-date",
          use_month_numbers: true,
          prompt:'--',
          start_year: (Time.now.year) - 5,
          end_year: (Time.now.year),
          date_separator: '%s'),
        "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
  </div>

  <div class="input-btn-contents">
    <%= f.submit "登録する", class:"input-btn" %>

    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>

  <%end%>
</div>

app/views/items/search.html.erb
<div id="top">
  <%= render "shared/header" %>
  <%= render "shared/nav" %>
</div>
<h2 class="title">SEARCH ITEM</h2>
<%# 検索結果の個数で条件分岐 %>
<div class="item_entry">
  <ul class="item-lists">
  <% if @results.length !=0 %>
  <% @results.each do |item| %>
    <li class='list'>
      <div class='item-info'>
        <h3 class='item-category'>
          <%= item.category.name %>
        </h3>
        <div class='item-season'>
          <%= item.season.name %>
        </div>
      </div>
      <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image.variant(resize:'119x160'), class: "item-img" %>
        </div>
      <%end%>
    </li>
  <% end %>
  <% else %>
  </ul>
  <div class="no-item">NO ITEM...</div>
  <% end %>
</div>


<div class="input-btn-contents">
  <%= link_to '戻る', root_path, class:"back-btn" %>
</div>

app/views/items/show.html.erb
<header>
<div id="top">
  <%= render "shared/header" %>
  <%= render "shared/nav" %>
</div>
</header>

<div class="item-show">
  <div class="item-mandatory">
    <h2 class="category-name">
      <span class="category-title">CATEGORY/</span>
      <%= @item.category.name %>
    </h2>
  </div>
  <div class="item-img-contents">
    <%= image_tag @item.image.variant(resize:'350x450'), class:"item-box-img" %>
  </div>
  <div class="item-explain-box">
    備考：
    <span><%= @item.explanation %></span>
  </div>
  <div class="item-remarks">
    <table>
    <tr>
      <th>シーズン</th>
      <td><%= @item.season.name %></td>
    </tr>
    <tr>
      <th>ブランド名</th>
      <td><%= @item.brand %></td>
    </tr>
    <tr>
      <th>購入日</th>
      <td><%= @item.purchase_day %></td>
    </tr>
    <tr>
      <th>購入金額</th>
      <td><%= @item.price %></td>
    </tr>
    <tr>
      <th>購入場所</th>
      <td><%= @item.place %></td>
    </tr>
    </table>
  </div>
  <div class="edit-btn">
    <% if user_signed_in? && current_user.id == @item.user_id %>
      <%= link_to '商品の編集',  edit_item_path(@item.id), method: :get, class: "item-edit-btn" %>
      <%= link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy' %>
    <% end %>
  </div>
  <div class="input-btn-contents">
    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCloset</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
    <meta name="Robots" content="index,follow">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_item_messages.erb
<%# 投稿後のエラーメッセージ %>
<% if model.errors.any? %>
  <p>投稿できていません！</p>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<%# ユーザー登録のエラーメッセージ %>
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div id="top">
  <h1><%= link_to 'My CLOSET', root_path, class: "top-text" %></h1>
</div>

app/views/shared/_item.html.erb
<% @item.each do |item| %>
  <li class='list'>
    <div class='item-info'>
      <h3 class='item-category'>
        <%= item.category.name %>
      </h3>
      <div class='item-season'>
        <%= item.season.name %>
      </div>
    </div>
    <%= link_to item_path(item.id) do %>
      <div class='item-img-content'>
        <%= image_tag item.image.variant(resize:'119x160'), class: "item-img" %>
      </div>
    <%end%>
  </li>
<% end %>

app/views/shared/_nav.html.erb
<div class='nav'>
  <ul class='lists-right'>
    <% if user_signed_in? %>
      <li class="user-nickname"><%= current_user.nickname %></li>
      <li><%= link_to 'カテゴリー追加', categories_path, class: "categories-btn" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
  </ul>
</div>